# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca687c5d6cda67414d0696f6d662f1f7f72388a698f74e6905f545b0d681c2aeff7642d6b91eb98cad4a0209265cf093127139ffd6536bcad1425b7610eff938

test:
  secret_key_base: 16ff5ae1dfcf90f73899fcc5a50f8102709af855a5236f9dea448e9087792075ab260afdeafe4c763aff40be394d15b295af1b1b145290d836c38b63906b846e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
